theme = "material_oceanic"


[editor]
cursor-shape.normal = "block"
cursor-shape.insert = "bar"
cursor-shape.select = "underline"
# rainbow-brackets = true

[keys.insert]
"C-[" = "normal_mode"
"C-m" = "insert_newline"
"C-space" = "completion"
"C-e" = "goto_line_end"
"C-b" = "move_char_left"
"C-f" = "move_char_right"

[keys.normal]
C-y = "scroll_up"
D   = "kill_to_line_end"
x = "extend_line_below"
X = "extend_line_above"
C-g = [
  ":write-all",
  ":new",
  ":insert-output jj diff",
  ":buffer-close!",
  ":redraw",
  ":reload-all"
]

[editor.indent-guides]
render = true
