[[language]]
name = "java"
language-servers = ["jdtls"]

[language-server.jdtls]
command = "jdtls"
args = ["--java-executable", "/Users/hirofumiomi/.local/share/mise/installs/java/21/bin/java"]

[language-server.angular-ls]
command = "ngserver"

args = ["--stdio"]

file-types = ["ts", "typescript", "html"]

[[language]]
name = "typescript"
language-servers = ["angular-ls", "typescript-language-server"]

[[language]]
name = "html"
language-servers = ["angular-ls", "vscode-html-languageservice"]

