theme = "material_oceanic"

[editor]
cursor-shape.normal = "block"
cursor-shape.insert = "bar"
cursor-shape.select = "underline"

[keys.insert]
"C-[" = "normal_mode"
"C-m" = "insert_newline"
"C-space" = "completion"
"C-e" = "goto_line_end"
"C-b" = "move_char_left"
"C-f" = "move_char_right"

[keys.normal]
"C-y" = "scroll_up"
"D"   = "kill_to_line_end"
