theme = "material_oceanic"

[editor]
cursor-shape.normal = "block"
cursor-shape.insert = "bar"
cursor-shape.select = "underline"

[keys.insert]
"C-]" = "normal_mode"
"C-m" = "insert_newline"

[keys.normal]
"C-y" = "scroll_up"
"C-e" = "scroll_down"
