#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
email = "99390907+omihirofumi@users.noreply.github.com"
name = "omihirofumi"

[ui]
merge-editor = ":builtin"
default-command = "log"
# Use Difftastic by default
diff-formatter = ["difft", "--color=always", "$left", "$right"]
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]

[colors]
change_id = "#ff1525"
