# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[aws]
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
symbol = 'AWS > '
style = 'bold yellow'
disabled = false

[custom.jj]
command = """
jj log -r @ --no-graph --template '
change_id.short()
++ " "
++ description.first_line()
++ if(conflict, "âš ï¸", "")
'
"""
when = "jj root"
format = "[ğŸª„ $output]($style) "
style = "bold purple"

# [gcloud]
# format = '[$symbol$account(@$domain)(\($region\))]($style) '
# symbol = 'ğŸ…¶ '
# style = 'bold blue'
# disabled = false
